name: visual-odometry
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.08.22
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.12
  - pip=23.3
  - python=3.11.5
  - readline=8.2
  - setuptools=68.0.0
  - sqlite=3.41.2
  - tk=8.6.12
  - tzdata=2023c
  - wheel=0.41.2
  - xz=5.4.2
  - zlib=1.2.13
  - pip:
    - numpy==1.26.2
    - opencv-python==4.8.1.78
    - black==23.11.0
    - pytest==7.4.3
